# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Andrew Schurman
url:              http://arcticwaters.github.io/blog
paginate:         1
baseurl:          /blog/
author:
  name:           Andrew Schurman
  email:          arcticwaters@gmail.com
timezone:         Canada/Pacific

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/arcticwaters/arcticwaters.github.io
